[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
crowdsol = "8tyRHod4FeXM6ZH4ELCm3JifjsKCd1A7fAPJZrxAqJEw"

[programs.devnet]
crowdsol = "8tyRHod4FeXM6ZH4ELCm3JifjsKCd1A7fAPJZrxAqJEw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./payer.json"

# cluster = "devnet"
# wallet = "/Users/aramburuaxel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
